# Generated by Django 5.1.2 on 2026-02-21 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeinterne',
            name='bordereau_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bordereaux_magasin/'),
        ),
        migrations.CreateModel(
            name='CommandeInterneAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('emission', 'Emission boutique'), ('expedition', 'Expedition magasin'), ('validation', 'Validation reception boutique'), ('annulation', 'Annulation')], max_length=20)),
                ('espace', models.CharField(choices=[('boutique', 'Boutique'), ('magasin', 'Magasin'), ('systeme', 'Système')], default='systeme', max_length=10)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_commandes_internes', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='magasin.commandeinterne')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
