# Generated by Django 5.1.2 on 2026-02-22 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_commandeinterne_bordereau_pdf_commandeinterneaudit'),
        ('produits', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeinterne',
            name='qr_token',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='StockMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_magasin', to='produits.produit')),
            ],
            options={
                'ordering': ('produit__nom',),
            },
        ),
    ]
