from django.urls import path
from .views import *
from .views import update_produit

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("produits/", produits, name="produits"),
    path("stock/", stock, name="stock"),
    path("stock/export/csv/", stock_export_csv, name="stock_export_csv"),
    path("stock/export/pdf/", stock_export_pdf, name="stock_export_pdf"),
    path("inventaire/", inventaire, name="inventaire"),
    path("inventaire/export/csv/", inventaire_export_csv, name="inventaire_export_csv"),
    path("inventaire/export/pdf/", inventaire_export_pdf, name="inventaire_export_pdf"),
    path("personnel/", personnel, name="personnel"),
    path("personnel/export/csv/", personnel_export_csv, name="personnel_export_csv"),
    path("personnel/export/pdf/", personnel_export_pdf, name="personnel_export_pdf"),
    path("salaires/", salaires, name="salaires"),
    path("salaires/export/csv/", salaires_export_csv, name="salaires_export_csv"),
    path("salaires/export/pdf/", salaires_export_pdf, name="salaires_export_pdf"),
    path("bons-achat/", bons_achat, name="bons_achat"),
    path("comptabilite/", comptabilite, name="comptabilite"),
    path("factures/", factures, name="factures"),
    path("factures/<int:vente_id>/marquer-payee/", facture_marquer_payee, name="facture_marquer_payee"),
    path("commandes-magasin/", commandes_magasin, name="commandes_magasin"),
    path("commandes-magasin/<int:commande_id>/valider/", valider_reception_commande_magasin, name="valider_reception_commande_magasin"),
    path("bon-commandes/", bon_commandes, name="bon_commandes"),
    path("bon-commandes/<int:bon_id>/pdf/", bon_commande_pdf, name="bon_commande_pdf"),
    path("proformas/", proformas, name="proformas"),
    path("proformas/<int:proforma_id>/pdf/", proforma_pdf, name="proforma_pdf"),
    path("proformas/<int:proforma_id>/ticket-a4/", proforma_ticket_a4_pdf, name="proforma_ticket_a4_pdf"),
    path("proformas/<int:proforma_id>/convertir/", proforma_convertir, name="proforma_convertir"),
    path("proformas/ajouter_panier/", ajouter_panier_proforma, name="ajouter_panier_proforma"),
    path("proformas/retirer_panier/", retirer_panier_proforma, name="retirer_panier_proforma"),
    path("proformas/vider_panier/", vider_panier_proforma, name="vider_panier_proforma"),
    path("proformas/modifier_quantite/", modifier_quantite_proforma, name="modifier_quantite_proforma"),
    path("proformas/modifier_prix_panier/", update_prix_panier_proforma, name="modifier_prix_panier_proforma"),
    path("proformas/supprimer_du_panier/", supprimer_du_panier_proforma, name="supprimer_du_panier_proforma"),
    path("proformas/remise_panier/", update_remise_panier_proforma, name="update_remise_panier_proforma"),
    path("remises/", remises_report, name="remises_report"),
    path("clients/", clients, name="clients"),
    path("ventes/", ventes, name="ventes"),
    path("facture/<int:vente_id>/", facture_pdf, name="facture_pdf"),
    path("ticket/<int:vente_id>/", ticket_caisse_pdf, name="ticket_caisse_pdf"),
    path("alerte/lue/<int:alerte_id>/", alertes_lues, name="alerte_lue"),
    # path('modification/<int:pk>/',update_donnee.as_view(), name='modifier'),
    # path('supprimer-produit/<int:pk>/', SuppressionProduit.as_view(), name='supprimer-produit'),
    # path('detail/<int:pk>/',edit.as_view(), name='detail'),
    path("ajouter_panier/", ajouter_panier, name="ajouter_panier"),
    path("retirer_panier/", retirer_panier, name="retirer_panier"),
    path("vider_panier/", vider_panier, name="vider_panier"),
    path("modifier_quantite/", modifier_quantite, name="modifier_quantite"),
    path("modifier_prix_panier/", update_prix_panier, name="modifier_prix_panier"),
    path("supprimer_du_panier/", supprimer_du_panier, name="supprimer_du_panier"),
    path("remise_panier/", update_remise_panier, name="update_remise_panier"),
    path("update-produit/<int:pk>/", update_produit, name="update_produit"),
    path('update-client/<int:pk>/', update_client, name='update_client'),
    path('ajouter-fournisseur/', ajouter_fournisseur, name='ajouter_fournisseur'),
    path('ajouter-categorie/', ajouter_categorie, name='ajouter_categorie'),


]
