# Generated by Django 5.1.2 on 2025-09-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='cheque_image',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
