# Generated by Codex on 2026-02-09

from django.db import migrations, models
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_stock_personnel_paie'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vente',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='discount_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='total_before_discount',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='remise_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='remise_value',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='total_ligne',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='BonAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type_remise', models.CharField(choices=[('percent', 'Pourcentage'), ('amount', 'Montant')], max_length=10)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('usages_max', models.IntegerField(default=0)),
                ('usages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
