# Generated by Codex on 2026-02-18

from django.db import migrations, models
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0005_remises_bon_achat"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12),
        ),
    ]
