# Generated by Codex on 2026-02-18

from django.db import migrations, models
import django.db.models.deletion
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0006_vente_commission"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonCommande",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("statut", models.CharField(choices=[("brouillon", "Brouillon"), ("valide", "Validé"), ("livre", "Livré"), ("annule", "Annulé")], default="brouillon", max_length=12)),
                ("note", models.TextField(blank=True, default="")),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                ("fournisseur", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="produits.fournisseur")),
                ("produit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="produits.produit")),
            ],
        ),
        migrations.CreateModel(
            name="FactureProforma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("remise", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("statut", models.CharField(choices=[("brouillon", "Brouillon"), ("envoyee", "Envoyée"), ("acceptee", "Acceptée"), ("expiree", "Expirée")], default="brouillon", max_length=12)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("client", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="produits.client")),
                ("produit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="produits.produit")),
            ],
        ),
    ]
