# Generated by Codex on 2026-02-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0007_boncommande_factureproforma"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproforma",
            name="date_conversion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factureproforma",
            name="vente_convertie",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="proformas_converties", to="produits.vente"),
        ),
    ]
