# Generated by Codex on 2026-02-18

from django.db import migrations, models
import django.db.models.deletion
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0008_factureproforma_conversion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproforma",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="factureproforma",
            name="coupon_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="factureproforma",
            name="coupon_discount",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="factureproforma",
            name="discount_type",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="factureproforma",
            name="discount_value",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="factureproforma",
            name="total_before_discount",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="factureproforma",
            name="total_discount",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12),
        ),
        migrations.CreateModel(
            name="LigneProforma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.IntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remise_type", models.CharField(blank=True, default="", max_length=10)),
                ("remise_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("total_ligne", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("produit", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="produits.produit")),
                ("proforma", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lignes", to="produits.factureproforma")),
            ],
        ),
    ]
