# Generated by Django 5.1.2 on 2026-02-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0014_ransonjournalier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gerant', 'Gérant'), ('caissier', 'Caissier'), ('comptable', 'Comptable'), ('magasinier', 'Magasinier')], default='caissier', max_length=20),
        ),
    ]
