# Generated by Django 5.1.2 on 2026-02-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_defectueuse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite_reparation',
            field=models.IntegerField(default=0),
        ),
    ]
