# Generated by Django 5.1.2 on 2026-02-23 01:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0016_produit_quantite_defectueuse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviProduitEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('classification', 'Classement défectueux'), ('envoi_reparation', 'Envoi réparation'), ('retour_reparation', 'Retour réparation'), ('rebut', 'Mise au rebut')], max_length=20)),
                ('etat_apres', models.CharField(choices=[('disponible', 'Disponible'), ('defectueux', 'Défectueux'), ('reparation', 'En réparation'), ('rebut', 'Rebut')], max_length=20)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('cout_reparation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date_prevue_retour', models.DateField(blank=True, null=True)),
                ('date_effective', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_etat', to='produits.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
