# Generated by Django 5.1.2 on 2026-03-09

from django.db import migrations, models


def normalize_product_image_paths(apps, schema_editor):
    Produit = apps.get_model("produits", "Produit")
    for produit in Produit.objects.exclude(image="").only("id", "image"):
        image_name = str(produit.image.name or "")
        if image_name.startswith("media/"):
            produit.image = image_name[len("media/") :]
            produit.save(update_fields=["image"])


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0017_suiviproduitetat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="produits/"),
        ),
        migrations.RunPython(
            normalize_product_image_paths,
            migrations.RunPython.noop,
        ),
    ]
